### ISSUE TITLE
Issues when compiling models with loops inside event handlers

### ISSUE THREAD

**Issue by lukius** [CIFASIS/qss-solver-mmoc#86]
`mmoc` has erratic behavior when compiling certain models that have loops that reference discrete variables inside event handlers. It might crash unexpectedly or otherwise it can generate a flawed C code (that can be manually fixed by changing some indices and variables). More information below:

 * Steps to reproduce the bug
   * Download [this sample model](https://github.com/CIFASIS/qss-solver-mmoc/files/3045079/helix_normal.zip) and open it in QSS Solver.
   * Press the `Compile and Run` button and observe the output. 
     * If `mmoc` crashes, compile it again.
     * Otherwise, scroll down and you should see an error displayed by the C compiler stating that variable `i` was not declared.
 * Software in use
   * QSS Solver v3.2 compiled from source (checked out in February, 2018)
   * Compiler: `gcc` 5.4.0
   * OS: Ubuntu 16.04 LTS 
 * Additional comments
   * The compilation error can be manually fixed by doing the following:
     * Using `i0` instead of `i` in the offending `for` loop.
     * Changing the loop condition from `i0 <= 0` to `i0 <= 19`.
     * Changing `modelData->event[0].nLHSDsc += 1;` to `modelData->event[0].nLHSDsc += 20;`.

**Comment by joaquinffernandez** [comment]
Fixed in a789708c754861beda37235de84c20b7405e3e47 in branch [mmoc-bug-fixes]

**Comment by lukius** [comment]
@joaquinffernandez, it seems this bug is still present. At first glance, changeset a789708 is apparently just dealing with code formatting issues, not introducing any actual change in the code. Can you confirm this?
